export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REQUEST_CATEGORY_START = 'REQUEST_CATEGORY_START';
export const REQUEST_CATEGORY_SUCCESS = 'REQUEST_CATEGORY_SUCCESS';
export const REQUEST_CATEGORY_FAIL = 'REQUEST_CATEGORY_FAIL';

export const CHANGE_SEARCH = 'CHANGE_SEARCH';

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const COMPARE_PRODUCT = 'COMPARE_PRODUCT';

export const CHANGE_REDIRECT = 'CHANGE_REDIRECT';
export const RESET_REDIRECT = 'RESET_REDIRECT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';